services:
  aspnetcoretemplate.api:
    image: aspnetcoretemplate.api
    build:
      context: .
      dockerfile: src/AspNetCoreTemplate.API/Dockerfile.development

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_DATABASE}'
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
